# Generated by Django 5.2.17 on 2026-09-09 09:00

import django.core.serializers.json
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RolloutFlag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=64, unique=True)),
                ('ruleset_name', models.CharField(max_length=64)),
                ('version', models.CharField(max_length=32)),
                ('percent', models.PositiveSmallIntegerField(default=0)),
                ('allowlist', models.JSONField(default=list)),
                ('enabled', models.BooleanField(default=True)),
                ('retire_by', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['created_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='DecisionRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ruleset_name', models.CharField(max_length=64)),
                ('ruleset_version', models.CharField(max_length=32)),
                ('subject_reference', models.CharField(max_length=128)),
                ('inputs', models.JSONField(encoder=django.core.serializers.json.DjangoJSONEncoder)),
                ('idempotency_key', models.CharField(max_length=64, unique=True)),
                ('flag_state', models.JSONField(default=dict)),
                ('outcome', models.CharField(choices=[('decided', 'Decided'), ('declined', 'Declined'), ('referred', 'Referred')], max_length=16)),
                ('stopped_at_stage', models.CharField(blank=True, default='', max_length=16)),
                ('decision', models.JSONField(default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'indexes': [models.Index(fields=['ruleset_name', 'ruleset_version', 'outcome'], name='record_ruleset_outcome'), models.Index(fields=['subject_reference'], name='record_subject'), models.Index(fields=['created_at'], name='record_created')],
            },
        ),
        migrations.CreateModel(
            name='ExceptionCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('open', 'Open'), ('resolved', 'Resolved')], default='open', max_length=16)),
                ('stage', models.CharField(max_length=16)),
                ('rule_name', models.CharField(max_length=128)),
                ('reason', models.TextField()),
                ('history', models.JSONField(default=list, encoder=django.core.serializers.json.DjangoJSONEncoder)),
                ('opened_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('resolved_by', models.CharField(blank=True, default='', max_length=128)),
                ('record', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='exception_case', to='engine.decisionrecord')),
            ],
            options={
                'ordering': ['opened_at', 'id'],
                'indexes': [models.Index(fields=['status', 'opened_at'], name='exception_status')],
            },
        ),
        migrations.CreateModel(
            name='StageOutcome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attempt', models.PositiveSmallIntegerField(default=1)),
                ('position', models.PositiveSmallIntegerField()),
                ('stage', models.CharField(max_length=16)),
                ('rule_name', models.CharField(max_length=128)),
                ('outcome', models.CharField(max_length=8)),
                ('reason', models.TextField()),
                ('values', models.JSONField(default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder)),
                ('overridden', models.BooleanField(default=False)),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stage_outcomes', to='engine.decisionrecord')),
            ],
            options={
                'ordering': ['attempt', 'position'],
                'indexes': [models.Index(fields=['stage', 'outcome'], name='stage_outcome_stage')],
                'constraints': [models.UniqueConstraint(fields=('record', 'attempt', 'position'), name='stage_outcome_position')],
            },
        ),
    ]
